<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>False</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\CK.SqlServer.Transaction\CK.SqlServer.Transaction.csproj" />
    <PackageReference Include="CK.Testing.SqlServer" Version="15.0.5--ci.4" />
    <PackageReference Include="CK.Testing.Nunit" Version="15.0.5--ci.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.3.0" />
  </ItemGroup>
</Project>