<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Description>
      Contains ISqlTransactionCallContext.
    </Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../CK.SqlServer/CK.SqlServer.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>
</Project>